### ISSUE TITLE
RuntimeError: Error getting zones from home: 32

### ISSUE THREAD

**Issue by rupertleveneucd** [ttroy50/pyephember#12]
Something seems to have changed and for the last couple of days my script is giving the error above. Here's an abbreviated test script which demonstrates the issue.

```
#!/usr/bin/env python3.4                                                                            
                                                                                                    
from pyephember.pyephember import EphEmber                                                          
                                                                                                    
ZONENAME="Zone 1"                                                                                   
ZONENAME="Hot Water"  
e = EphEmber('my.email@address.com', 'password')
print(e.get_zone_temperature(ZONENAME))      
```                                                       

Output:

```
Traceback (most recent call last):
  File "./ember-test.py", line 9, in <module>
    print(e.get_zone_temperature(ZONENAME))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyephember/pyephember.py", line 321, in get_zone_temperature
    zone = self.get_zone(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyephember/pyephember.py", line 301, in get_zone
    for zone in self.get_zones():
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyephember/pyephember.py", line 281, in get_zones
    home_data = self.get_home()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyephember/pyephember.py", line 273, in get_home
    "Error getting zones from home: {}".format(status))
RuntimeError: Error getting zones from home: 32

```

**Comment by ttroy50** [comment]
This might be related to #11 and the API change. Unfortunately I haven't had time to fully look into the API change
