### ISSUE TITLE
`pointIndex` of mode now 11 instead of 7

### ISSUE THREAD

**Issue by MarcDonald** [ttroy50/pyephember#17]
## Issue

Unsure if related to #11 but it seems that the `pointIndex` for mode is now 11 instead of 7. Due to this I'm seeing the following errors in version 4.0.0:

```
  File "/workspaces/home-assistant-core/homeassistant/components/ephember/climate.py", line 127, in hvac_mode
    mode = zone_mode(self._zone)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pyephember/pyephember.py", line 248, in zone_mode
    return ZoneMode(zone_pointdata_value(zone, 'MODE'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc

ValueError: 350 is not a valid ZoneMode
```

**_ValueError: 350 is not a valid ZoneMode_**

## System Info
System Type: EMBER-TS1

## API Responses

_Other point indexes left out for brevity, but they did not change when switching between modes_

AUTO:
```
    "pointDataList": [
        {"pointIndex": 7, "value": "350"},
        {"pointIndex": 11, "value": "0"},
    ],
```

MANUAL:
```
    "pointDataList": [
        {"pointIndex": 7, "value": "350"},
        {"pointIndex": 11, "value": "1"},
    ],
```

OFF:
```
    "pointDataList": [
        {"pointIndex": 7, "value": "350"},
        {"pointIndex": 11, "value": "4"},
    ],
```

**Comment by Zaduvalo** [comment]
It looks like pointIndex 11 has different values for each device type.

R37RF V2 programmer:
"systemType": "EMBER-PS2"
"deviceType": 514,
PointIndex 11 values:
Auto = 0
Off = 4
All Day = 9
On = 10

eTRV - radiator valve:
"systemType"= "EMBER-RS"
"deviceType" = 773
PointIndex 11 values:
Auto = 0
Manual = 1
Off = 4

We need to build a map indexes and values for each device type or system type.
Possibly some devices keep using pointIndex 7.

**Comment by Jesus-M** [comment]
pointDataList for my zones:

```
"deviceType": 2,
"name": "Downstairs", (mode ON)
"pointDataList": [
    {"pointIndex":  3,"value": "13"},
    {"pointIndex":  4,  "value": "0"},
    {"pointIndex":  5,"value": "206"},
    {"pointIndex":  6,"value": "215"},
    {"pointIndex":  7,"value": "2"},
    {"pointIndex":  8,"value": "0"},
    {"pointIndex":  9,"value": "0"},
    {"pointIndex": 10,"value": "2"},
    {"pointIndex": 11,"value": "0"},
    {"pointIndex": 13,"value": "1"},
    {"pointIndex": 14,"value": "195"},
    {"pointIndex": 15,"value": "28574132"},
    {"pointIndex": 16,"value": "0"},
    {"pointIndex": 18,"value": "4601106"},
    {"pointIndex": 17,"value": "326701945"}
  ],
"systemType": "EMBER-PS",
```

```
"deviceType": 2,
"name": "Upstairs", (mode ON)
"pointDataList": [
    {"pointIndex":  3,"value": "13"},
    {"pointIndex":  4,"value": "0"},
    {"pointIndex":  5,"value": "214"},
    {"pointIndex":  6,"value": "210"},
    {"pointIndex":  7,"value": "2"},
    {"pointIndex":  8,"value": "0"},
    {"pointIndex":  9,"value": "0"},
    {"pointIndex": 10,"value": "1"},
    {"pointIndex": 11,"value": "0"},
    {"pointIndex": 13,"value": "1"},
    {"pointIndex": 14,"value": "185"},
    {"pointIndex": 15,"value": "1832058880"},
    {"pointIndex": 16,"value": "313720832"},
    {"pointIndex": 17,"value": "0"},
    {"pointIndex": 18,"value": "0"}
  ],
"systemType": "EMBER-PS",
```

```
"deviceType": 2,
"name": "Attic",  (mode ON)
"pointDataList": [
    {"pointIndex":  3,"value": "13"},
    {"pointIndex":  4,"value": "0"},
    {"pointIndex":  5,"value": "170"},
    {"pointIndex":  6,"value": "160"}
    {"pointIndex":  7,"value": "2"},
    {"pointIndex":  8,"value": "0"},
    {"pointIndex":  9,"value": "0"},
    {"pointIndex": 10,"value": "1"},
    {"pointIndex": 11,"value": "1"},
    {"pointIndex": 13,"value": "1"},
    {"pointIndex": 14,"value": "160"},
    {"pointIndex": 15,"value": "1841758208"},
    {"pointIndex": 16,"value": "313720832"},
    {"pointIndex": 17,"value": "0"},
    {"pointIndex": 18,"value": "0"},
  ],
"systemType": "EMBER-PS",
```

```
"deviceType": 4,
"name": "Hot Water", (mode AUTO)
"pointDataList": [
    {"pointIndex":  3,"value": "12"},
    {"pointIndex":  4,"value": "0"},
    {"pointIndex":  5,"value": "550"},
    {"pointIndex":  6,"value": "550"},
    {"pointIndex":  7,"value": "0"},
    {"pointIndex":  8,"value": "0"},
    {"pointIndex":  9,"value": "0"},
    {"pointIndex": 10,"value": "1"},
    {"pointIndex": 11,"value": "0"},
    {"pointIndex": 13,"value": "1"},
    {"pointIndex": 14,"value": "550"},
    {"pointIndex": 15,"value": "1841758208"},
    {"pointIndex": 16,"value": "313720832"},
    {"pointIndex": 17,"value": "0"}
    {"pointIndex": 18,"value": "0"},
  ],
"systemType": "EMBER-PS",
```

**Comment by Zaduvalo** [comment]
@Jesus-M thanks, can you add device model names, please? It will help to understand what we supporting.
I think all your devices (two types) use pointIndex 7 for modes. Can you confirm current values are correct?
AUTO = 0
ALL_DAY = 1
ON = 2
OFF = 3

**Comment by Jesus-M** [comment]
ok, this is my system, hope this helps


```
"systemType": "EMBER-PS" (EMBERPS04 - 4 zones)
WiFi Gateway: GW01
```

```
HotWater: RFR/A2202B
deviceType: 4
pointDataList/pointIndex: 7
  AUTO:    0
  ALL_DAY: 1
  ON:      2
  OFF:     3
```
```
Regular: RFR/A2228C
deviceType: 2
pointDataList/pointIndex: 7
  AUTO:    0
  ALL_DAY: 1
  ON:      2
  OFF:     3
```

**Comment by roberty99** [comment]
'deviceType': 4,
'isonline': True,
'mac': '******',
'name': 'Hot Water',
'pointDataList': [{'pointIndex': 6, 'value': '500'},
{'pointIndex': 13, 'value': '1'},
{'pointIndex': 10, 'value': '1'},
{'pointIndex': 4, 'value': '0'},
{'pointIndex': 14, 'value': '500'},
{'pointIndex': 15, 'value': '79692992'},
{'pointIndex': 5, 'value': '395'},
{'pointIndex': 17, 'value': '0'},
{'pointIndex': 18, 'value': '1389712085'},
{'pointIndex': 8, 'value': '0'},
{'pointIndex': 16, 'value': '0'},
{'pointIndex': 7, 'value': '3'},
{'pointIndex': 9, 'value': '0'},
{'pointIndex': 11, 'value': '0'},
{'pointIndex': 3, 'value': '12'}],

'deviceType': 2,
'isonline': True,
'mac': '********',
'name': 'Radiators',
'pointDataList': [{'pointIndex': 11, 'value': '0'},
{'pointIndex': 4, 'value': '0'},
{'pointIndex': 14, 'value': '215'},
{'pointIndex': 17, 'value': '21575'},
{'pointIndex': 16, 'value': '2616000512'},
{'pointIndex': 7, 'value': '3'},
{'pointIndex': 6, 'value': '215'},
{'pointIndex': 13, 'value': '1'},
{'pointIndex': 5, 'value': '182'},
{'pointIndex': 9, 'value': '0'},
{'pointIndex': 18, 'value': '11075705'},
{'pointIndex': 15, 'value': '320057263'},
{'pointIndex': 3, 'value': '13'},
{'pointIndex': 10, 'value': '1'},
{'pointIndex': 8, 'value': '0'}],

**Comment by Zaduvalo** [comment]
Hi all, I am preparing a new pyephember version. eTrv and R37-RF-V2 limited support added. Advance and Boost modes are not supported. Temperature could be set only in ON/Manual mode

Can you test your devices, I hope they will work as normal.

PR to continue work
https://github.com/ttroy50/pyephember/pull/19

HA draft pool request
https://github.com/home-assistant/core/pull/140459

To test you can copy-paste pyephember.py and climate.py files from PRs above.

@MarcDonald can you check your 'deviceType' id please

**Comment by Jesus-M** [comment]
My HA system is running over generic x86-64 pc and I have no access (or don't know how to get) to the pyephember file. Can modify the climate.py but not the python module.

**Comment by Zaduvalo** [comment]
Strange, all files should be on same pc.
I am running from Docker and files located in:
/usr/src/homeassistant/homeassistant/components/ephember/climate.py
/usr/local/lib/python3.13/site-packages/pyephember/pyephember.py

`dir "/pyephember.py" /s`

**Comment by Jesus-M** [comment]
I don't have access (or don't know how to access) to the host machine:

```
# telnet 172.16.0.5
Trying 172.16.0.5...
telnet: connect to address 172.16.0.5: Connection refused
# ssh 172.16.0.5
ssh: connect to host 172.16.0.5 port 22: Connection refused
#
```

I am using the 'terminal' addon and this is what i get:

![Image](https://github.com/user-attachments/assets/8868c3c2-36b4-4997-932b-c8db199ce7a1)

I would love to know how to access, but I don't ...

**Comment by Zaduvalo** [comment]
Better to not change your main HA instance.
Instead, you can try to setup dev environment.
You need to install Visual Studio Code and Docker Desktop. And use this link to run environment -> https://developers.home-assistant.io/docs/development_environment/

/home/vscode/.local/ha-venv/lib/python3.13/site-packages/pyephember/pyephember.py
/workspaces/coreEPH/homeassistant/components/ephember/climate.py

**Comment by Jesus-M** [comment]
the reason I installed HA on a generic_x86-64 device is because after many attempts I was completely unable to set a virtual environment, it's completely out of my reach.

**Comment by roberty99** [comment]
I am setup in a VisualStudio Code Dev Container but I cannot find how to swop out the pyephember.py file for that library.

**Comment by roberty99** [comment]
@Zaduvalo getting the following error with your code. 

"Home" is the name of my Home and inside I have two zones. 

2025-03-13 14:13:01.909 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.home fails
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/workspaces/core/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspaces/core/config/custom_components/old_ephember/climate.py", line 186, in update
    self._zone = self._ember.get_zone(self._zone_name)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/workspaces/core/config/pyephember/pyephember/pyephember.py", line 977, in get_zone
    raise RuntimeError("Unknown zone: %s" % zoneid)
RuntimeError: Unknown zone: Home

**Comment by Zaduvalo** [comment]
@roberty99 you need to replace climate.py -> https://github.com/home-assistant/core/blob/3b1fbb4088fac795a78391e8fef58c798d159dda/homeassistant/components/ephember/climate.py

All functions with names replaced, name is not a zone identifier.

**Comment by roberty99** [comment]
okay figured it out . It was picking up my Custom Component folder even though it was renamed. 
I am testing now ! but at a high level basic functions are working for my two zones. 
If I get a reproduceable bug I'll let you know the steps and error output. 
Thanks for helping me on this !

**Comment by roberty99** [comment]
Here is one reproduceable error when switching modes now. 

2025-03-13 15:29:51.412 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140017450333672] Unexpected exception
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/workspaces/core/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/workspaces/core/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/helpers/service.py", line 1014, in entity_service_call
    await entity.async_update_ha_state(True)
  File "/workspaces/core/homeassistant/helpers/entity.py", line 978, in async_update_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/workspaces/core/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/workspaces/core/homeassistant/helpers/entity.py", line 1087, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/components/climate/__init__.py", line 444, in state_attributes
    if hvac_action := self.hvac_action:
                      ^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/components/ephember/climate.py", line 152, in hvac_action
    if zone_is_active(self._zone):
       ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/workspaces/core/config/pyephember/pyephember/pyephember.py", line 154, in zone_is_active
    elif zone_is_scheduled_on(zone):
         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/workspaces/core/config/pyephember/pyephember/pyephember.py", line 278, in zone_is_scheduled_on
    runningPrograms = zone_get_running_program(zone)
  File "/workspaces/core/config/pyephember/pyephember/pyephember.py", line 228, in zone_get_running_program
    p_time = scheduletime_to_time(program["time"])
                                  ~~~~~~~^^^^^^^^
KeyError: 'time'

**Comment by roberty99** [comment]
If it helps here is the messagelogger output when setting the mode for each Zone.  


13 Mar 2025 16:27:47 Subscribed with data: (None,1,[ReasonCode(Suback, 'Granted QoS 0')])

13 Mar 2025 16:27:59 pointData: {7: ('MODE', 1, '0', 0), 15: ('CTR_15_ABAB', 5, '19.19.175.175', 320057263), 16: ('XXX_16_0000', 5, '24.93.0.0', 408748032), 17: ('CTR_17_ABAB', 5, '0.0.24.101', 6245), 18: ('CTR_18_0AB7', 5, '0.110.0.69', 7209029)}

13 Mar 2025 16:28:10 pointData: {7: ('MODE', 1, '0', 0), 15: ('CTR_15_ABAB', 5, '1.145.1.145', 26280337), 16: ('XXX_16_0000', 5, '0.0.0.0', 0), 17: ('CTR_17_ABAB', 5, '0.0.0.0', 0), 18: ('CTR_18_0AB7', 5, '23.244.23.241', 401872881)}

**Comment by Zaduvalo** [comment]
> KeyError: 'time'

This one should be fixed. Please test the new version.
This function should find an active Schedule program. If the zone is active you will see 'heating' message in the climate card.

<img width="363" alt="Image" src="https://github.com/user-attachments/assets/5f3788ba-a7f9-402f-9b66-3df705a2f4ba" />

This function was heavily refactored. Now it should support unlimited/dynamic number of day programs and support new way of program data.

**Comment by roberty99** [comment]
All working good now !

![Image](https://github.com/user-attachments/assets/16daa432-ce53-41d7-94eb-f3e0c0d9d6f3)

**Comment by Zaduvalo** [comment]
Great! Check later 'heating' status.
This status calculated by current program is active and program's target temp is less than the current temp. This is not an ideal solution, but we don`t have proper data to identify heating/idle statuses.

**Comment by roberty99** [comment]
I'll check later tonight. 
I might actually move to Scheduler cardw instead of Ember schedules going forward if we get all this fixed finally !  

![Screenshot_2025-03-13-17-31-43-47_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/508468f1-1f8f-4593-bb56-b5690cadc9b6)

**Comment by roberty99** [comment]
I am tring today in my production instance and getting this error. 
any ideas where to check ? seems it's correctly using custom_components/ephember which has your climate.py. 
Also in terminal I built your package for pyephember with pip install -e ./pyephember

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:382
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 4:01:45 PM (1 occurrences)
Last logged: 4:01:45 PM

Error while setting up ephember platform for climate: 'zones'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ephember/climate.py", line 87, in setup_platform
    for zone in home["zones"]:
                ~~~~^^^^^^^^^
KeyError: 'zones'

**Comment by Zaduvalo** [comment]
It takes the wrong pyephember version, old version did not have "zones". Try to search all locations of pyephember.py library and replace them with the right one. 
requirements file still contains an older version of pyephember and may be pip updates library to the required old version

**Comment by roberty99** [comment]
> It takes the wrong pyephember version, old version did not have "zones". Try to search all locations of pyephember.py library and replace them with the right one. requirements file still contains an older version of pyephember and may be pip updates library to the required old version

Thank you for pointing me in right direction. Updated my pyephember2 package with your file and set the climate.py to use that. All working now. I can test for a few more days on my production instance but looks working well.

**Comment by Jesus-M** [comment]
So, if this is working fine, is someone gonna try to push a new PR and see if this time it passes?

Thanks

**Comment by roberty99** [comment]
I've had perfect stability the past week using both climate.py and pyephember versions provided.  All my heating automations and manual calls have worked as well as temp and status readings. ![Screenshot_2025-03-24-14-58-16-64_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/0f785912-969c-41e9-98a1-9cc93cd2c4de)

**Comment by Zaduvalo** [comment]
Hi @roberty99, good to hear this version is stable. Could you create new version in https://pypi.org/project/pyephember2/ ? After that, we can push HA changes -> https://github.com/home-assistant/core/pull/140459

I think there is no reason to wait for the original repo owner.

**Comment by roberty99** [comment]
Pyephember2 now updated and credits ttroy50 for pyephember.

**Comment by Zaduvalo** [comment]
PR opened -> https://github.com/home-assistant/core/pull/140459

**Comment by Zaduvalo** [comment]
Hi @roberty99 , could you publish a new version please. Some code moved from HA to pyephember.

Latest version is here
https://github.com/Zaduvalo/pyephember/blob/HA_refactoring/pyephember/pyephember.py

**Comment by roberty99** [comment]
> Hi [@roberty99](https://github.com/roberty99) , could you publish a new version please. Some code moved from HA to pyephember.
> 
> Latest version is here https://github.com/Zaduvalo/pyephember/blob/HA_refactoring/pyephember/pyephember.py

Complete now. Version 0.4.11

**Comment by Zaduvalo** [comment]
@roberty99 thanks, HA PR updated

**Comment by Jesus-M** [comment]
it seems the fix didn't come with today's update :-(

**Comment by Zaduvalo** [comment]
I did not get update. My current HA version 2025.2.5. This version is updated or old?

**Comment by Zaduvalo** [comment]
They are using RC branch to build releases and tags, really no changes for eph.
https://github.com/home-assistant/core/blob/rc/homeassistant/components/ephember/manifest.json

**Comment by Jesus-M** [comment]
There were today a core update, 2025.4.3.

This is what I am running 
![image](https://github.com/user-attachments/assets/9eff9404-cd8c-4e8e-bba8-5c4e0f9d6d31)

**Comment by Zaduvalo** [comment]
Probably it will be added to the next release candidate.

**Comment by Jesus-M** [comment]
And again a core update (2025.4.4) without the update ☹️
![image](https://github.com/user-attachments/assets/dfd385be-7524-4f08-bd00-25ae7a6b42f2)

But apparently the update is there:

https://github.com/home-assistant/core/blob/dev/homeassistant/components/ephember/manifest.json

**Comment by roberty99** [comment]
It's the RC release Candidate branch you want to be checking. 

the branches seem to be Dev --> RC --> Tagged release version

https://github.com/home-assistant/core/blob/rc/homeassistant/components/ephember/manifest.json

**Comment by Jesus-M** [comment]
yes, but I wonder why this change is not yet in the RC branch. I checked all the merges included in the new udpate and all them were pushed after this one

**Comment by Zaduvalo** [comment]
I am preparing the next PR for cutted changes and asked a question about releases. Maybe somebody can answer how releases work.
https://github.com/home-assistant/core/pull/143180

**Comment by Jesus-M** [comment]
> It will be in the next Beta and subsequent release. Version bumps usually do not go into point releases.

hmmm

![Image](https://github.com/user-attachments/assets/e3da0e7a-13de-41ad-94fa-1cd149ba461a)
